function calculate_mean_normals_test()

n_flat = [ ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    nan nan nan; ...
    ];
reorder = [ 1 3 5 2 4 6 ];
n_flat_jumble = n_flat( reorder, : );
n_inside = [ ...
    0 0 1; ...
    1 1 1; ...
    -1 1 1; ...
    -1 -1 1; ...
    1 -1 1; ...
    nan nan nan; ...
    ];
n_outside = [ ...
    0 0 1; ...
    -1 -1 1; ...
    1 -1 1; ...
    1 1 1; ...
    -1 1 1; ...
    nan nan nan; ...
    ];
n_outside_double = n_outside;
n_missing = [ ...
    0 0 1; ...
    1 -1 1; ...
    0 1 1; ...
    -1 -1 1; ...
    nan nan nan; ...
    nan nan nan; ...
    ];
n_missing_ck = [ ...
    0 0 1; ...
    1 -1 1; ...
    0 1 1; ...
    -1 -1 1; ...
    0 -1 1; ...
    nan nan nan; ...
    ];
normals = cat( 3, n_flat, n_flat_jumble, n_inside, n_outside, ...
    n_outside_double, n_missing, n_missing_ck );
normals = permute( normals, [ 1 3 2 ] );
normals = normals ./ vecnorm( normals, 2, 3 );
mean_normals = normals( 1, :, : );

COUNT = 1;
normals = repmat( normals, [ 1 COUNT 1 ] );
normals_count = size( normals, 2 );
fprintf( "normals: %i\n", normals_count );
t = tic;
mean_normals = calculate_mean_normals( normals );
toc( t );

end

