function sort_points_counterclockwise_test()

flat = [ ...
    0 0 0; ...
    -1 -1 0; ...
    1 -1 0; ...
    1 1 0; ...
    -1 1 0; ...
    nan nan nan; ...
    ];
reorder = [ 1 3 5 2 4 6 ];
flat_jumble = flat( reorder, : );
missing = [ ...
    0 0 0; ...
    1 -1 -1; ...
    0 1 -1; ...
    -1 -1 -1; ...
    nan nan nan; ...
    nan nan nan; ...
    ];
missing_ck = [ ...
    0 0 0; ...
    1 -1 -1; ...
    0 1 -1; ...
    -1 -1 -1; ...
    0 -1 -1; ...
    nan nan nan; ...
    ];
points = cat( 3, flat, flat_jumble, missing, missing_ck );
points = permute( points, [ 1 3 2 ] );

n_flat = [ ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    nan nan nan; ...
    ];
n_flat_jumble = n_flat( reorder, : );
n_missing = [ ...
    0 0 1; ...
    1 -1 1; ...
    0 1 1; ...
    -1 -1 1; ...
    nan nan nan; ...
    nan nan nan; ...
    ];
n_missing_ck = [ ...
    0 0 1; ...
    1 -1 1; ...
    0 1 1; ...
    -1 -1 1; ...
    0 -1 1; ...
    nan nan nan; ...
    ];
normals = cat( 3, n_flat, n_flat_jumble, n_missing, n_missing_ck );
normals = permute( normals, [ 1 3 2 ] );
normals = normals ./ vecnorm( normals, 2, 3 );
mean_normals = normals( 1, :, : );

COUNT = 1;
points = repmat( points, [ 1 COUNT 1 ] );
mean_normals = repmat( mean_normals, [ 1 COUNT 1 ] );
center_point_count = size( points, 2 );
fprintf( "center_points: %i\n", center_point_count );
t = tic;
inds = sort_points_counterclockwise( points, mean_normals );
toc( t );

end

